### ISSUE TITLE
Rabbit + Scylla Throughput Testing

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#802]
### Goal
Stress test the write throughput of rabbit + scylla when geyser is pushing all accounts and transactions (except for votes).

### Tasks
- [ ] Standup a scylla instance to act as solana datalake
- [ ] Configure new queue for rabbit for sending the firehouse of events
- [ ] Modify existing indexer plugin to send transaction events instead of individual instructions
- [ ] Modify existing indexer consumer to write accounts and transactions to scylla
- [ ] Run test through production standby validator
- [ ] Document key metrics
  - Time to index accounts when start up true
  - Processing time over 48H test run
  - Resource usage of Rabbit and Scylla when all Solana accounts recorded
  - Query time of looking up an account by address and transaction by signature when all Solana accounts recorded
