### ISSUE TITLE
Moonrank Collection Indexing

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#805]
## Goal
Index moonrank collections and NFTs associated to the collection.

## Requirements
- All moonrank collections are saved into the indexer database
- All mint lists associated to moonrank collections are saved into the indexer database

## Resources
- [Moon rank API](https://gist.github.com/moonrank/3e27b3e2572438f1db0caf700c6928c7)

## Tasks
- [ ] Create database tables for storing the collections and linking collection identifier to nft mint address
- [ ] Cron based script for fetching the collection list. Adding or updating records. And enqueuing job to write the mint list.
- [ ] Worker job of indexer that maps the MR identifier to mint address of the NFT

## Tables
```
collections
-----------
id [primary key]
image 
name
description
twitter_url
discord_url
website_url
magic_eden_identifier [index]
verified
pieces
go_live_at
verified_collection_address
created_at
updated_at
```

```
collection_nfts
---------------
collection_id [index]
metadata_mint_address [index]
(collection_id, metadata_mint_address) [primary key]
```

**Comment by kespinola** [comment]
## Follow up issues
- [ ] Drop me collection tables and crons
- [ ] Move collection trends to be based off of collections table solely
- [ ] Index collections into meli search based on moon rank collections
-----
- [ ] Make all queries use collections table instead of union mcc + me collections [anshul]
