### ISSUE TITLE
Wallets Rewards Earned

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#812]
## Goal
Provide quick lookup of the total rewards earned for a wallet.

## Requirements
- Counter cache table per user and reward center
- Query total rewards earned for a user given the reward center as an argument

## Tasks
- [x] Create a table to track the total rewards earned of a user
```
wallet_total_rewards
---------------------
id [uuid primary_key]
wallet_address
reward_center_address
total_rewards

idx (wallet_address, reward_center_address)
```
- [x] Add postgres function and trigger on reward_payouts create that updates the total rewards for the buyer and the seller
- [x] Include field on wallet to get the total rewards given a reward_center
```graphql
wallet(addres: "$walletAddress") {
  totalRewards(rewardCenter: "$rewardCenterAddress")
}
```

**Comment by kespinola** [comment]
done.
