### ISSUE TITLE
Setting Up Hasura Caching on Staging

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#823]
### Goal
Indexer API proxied through Hasura to enable query ttl based query cacheing.

###  Tasks
- [x] Start paying Hasura @kespinola
- [x] VPC peer Hasura with Hoalplex @mpwsh 
- [x] Update API DNS for staging and production to Hasura endpoints @mpwsh 
graph.dev.holaplex.tools
- [x] Configure Hasura project upstreams to Holaplex Graph API using internal addressable fqdn @mpwsh

**Comment by kespinola** [comment]
- [ ] Test case of running graph-test through Hasura proxy.

graph-test.holaplex.com

**Comment by kespinola** [comment]
graph.dev.holaplex.com

**Comment by mpwsh** [comment]
https://github.com/holaplex/dao-marketplace/pull/195
