### ISSUE TITLE
Index v0.2.1 of Reward Center Program

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#842]
### Goal
Index updated accounts and instructions for the reward center program.

```
RwDDvPp7ta9qqUwxbBfShsNreBaSsKvFcHzMxfBC3Ki
```

### Tasks
- [ ] Update program address
- [ ] Adjust account indexing based on new version of listing, offer, and remove of payment ticket.
- [ ] Index close_offer, close_listing, and execute_sale instructions
- [ ] Replace the canceled_at on offers and listings with canceled_at based on the time of indexing the close instructions
- [ ] Replace purchase_ticket with purchase_id to be based on the accounts and arguments of execute sale
- [ ] Write reward_payouts as part of execute_sale

### References
https://crates.io/crates/hpl-reward-center/0.2.1
